// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLTjTPKkN63OvljpRw13hzKvvnbapiOLU',
    appId: '1:1006294623000:web:e9042d0e74f836e9e9746d',
    messagingSenderId: '1006294623000',
    projectId: 'wanderplan-ea9f4',
    authDomain: 'wanderplan-ea9f4.firebaseapp.com',
    storageBucket: 'wanderplan-ea9f4.firebasestorage.app',
    measurementId: 'G-LEXTW4ZTMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFV0FRU8Hczk52P1DSWo57cbD3ldRJdc4',
    appId: '1:1006294623000:android:bcd99deea3ecfd9de9746d',
    messagingSenderId: '1006294623000',
    projectId: 'wanderplan-ea9f4',
    storageBucket: 'wanderplan-ea9f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIZbeoTW4EmlzDfHJobL2exuU-RTYem34',
    appId: '1:1006294623000:ios:ff2b0bc8c04644bae9746d',
    messagingSenderId: '1006294623000',
    projectId: 'wanderplan-ea9f4',
    storageBucket: 'wanderplan-ea9f4.firebasestorage.app',
    iosClientId: '1006294623000-96bu5j3ngo6oblhs4ndnu46fij1acna4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wanderplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIZbeoTW4EmlzDfHJobL2exuU-RTYem34',
    appId: '1:1006294623000:ios:ff2b0bc8c04644bae9746d',
    messagingSenderId: '1006294623000',
    projectId: 'wanderplan-ea9f4',
    storageBucket: 'wanderplan-ea9f4.firebasestorage.app',
    iosClientId: '1006294623000-96bu5j3ngo6oblhs4ndnu46fij1acna4.apps.googleusercontent.com',
    iosBundleId: 'com.example.wanderplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLTjTPKkN63OvljpRw13hzKvvnbapiOLU',
    appId: '1:1006294623000:web:9d3f22a8b40c2c47e9746d',
    messagingSenderId: '1006294623000',
    projectId: 'wanderplan-ea9f4',
    authDomain: 'wanderplan-ea9f4.firebaseapp.com',
    storageBucket: 'wanderplan-ea9f4.firebasestorage.app',
    measurementId: 'G-JZGRK5TMSZ',
  );
}
